### ISSUE TITLE
Please submit to Artifact Hub

### ISSUE THREAD

**Issue by mattfarina** [spegel-org/spegel#362]
Could you please submit the helm chart to https://artifacthub.io/. This would make it more discoverable.

**Comment by phillebaba** [comment]
@mattfarina I have moved the repository to a new org so I have now published the Helm chart to Artifact Hub. Will go back and add verification metadata to the chart at a later time.

https://artifacthub.io/packages/helm/spegel/spegel

Closing this as completed.
