### ISSUE TITLE
Move to a new GitHub organization

### ISSUE THREAD

**Issue by phillebaba** [spegel-org/spegel#374]
Usage of Spegel has over the last year grown a lot more than I expected. On top of that it is also included as a feature in k3s now. This means that the project requires stability and trust for future development. I am still the main developer of Spegel and I suspect that to be the case for the coming future. I will be leaving Xenit soon and as there is no one else to take over, I think it is best that we move Spegel to a new GitHub organization that is not affiliated to a specific company. That would allow me to continue development without my current employer affecting the project.

There are a few considerations when moving organization that we have to make sure will not break existing users, and give them reasonable time to update their deployments.

- [x] Decide on name for the new organization or find and existing organization to move to.
- [x] Verify that moving the repository will not break existing image artifacts.
- [x] Execute the move.
- [x] Update Go imports in Spegel.
- [x] Update Go import in k3s.
- [x] Make first release in new org.
- [x] Copy existing artifacts to new org.

**Comment by bittrance** [comment]
Agreed. I think going to a separate org is the sensible/responsible thing to do in this situation. Unless you have a relevant cooperative organisation where you have contacts (I don't, unless you count CNCF), I think a new org would be the natural choice, e.g. spegelorg.

**Comment by simongottschlag** [comment]
The sensible choice in my opinion is a new org which you have full control over regardless of employer.

**Comment by phillebaba** [comment]
Sadly Spegel is already taken by someone else, org names can't conflict with users. @bittrance suggested `spegelorg` which would be an alternative.

I am taking suggestions if anyone else has a better name that is available.

**Comment by phillebaba** [comment]
I talked to @NissesSenap who recently made a similar move of [grafana-operator](https://github.com/grafana/grafana-operator) to the Grafana org. There were no major incidents during their move. Moving repositories does not affect the artifacts, we should however copy over the existing releases to the new org to preserve them.

**Comment by phillebaba** [comment]
I have now moved the repository to the new org `spegel-org` will get going on completing the other tasks and cut a first release in this org.

**Comment by bittrance** [comment]
@phillebaba As far as I can tell, the spegel deps are updated in k3s and this issue can be closed. Ref https://github.com/k3s-io/k3s/blob/fe7d114c6a462bc0c372e4011e6a3dae318e74e4/go.mod#L132 (replaced by fork from spegel-org).
