### ISSUE TITLE
Include Grafana dashboards as option to enable in Helm charts

### ISSUE THREAD

**Issue by onedr0p** [spegel-org/spegel#387]
### Describe the problem to be solved

Hi 👋🏼

It would nice if we could bundle the Grafana dashboards for spegel in the Helm chart, here are a couple examples of projects doing this:

- https://github.com/cilium/cilium/blob/95c916d3044f9783dfbfa43f26f6adc5765544d5/install/kubernetes/cilium/values.yaml#L940-L947
- https://github.com/cloudnative-pg/charts/blob/866413fbf8fc31e659cb98d41fff222eeb9c8006/charts/cloudnative-pg/values.yaml#L142-L151

### Proposed solution to the problem

Having the Grafana dashboards be included in the Helm chart would be awesome as it would bundle them up as a straightforward way to deploy and get updates.

**Comment by phillebaba** [comment]
After thinking about it I would be fine with adding a Grafana dashboard to the repo, and having it be a part of the Helm chart.

Maybe @fberube could help us with the Grafana dashboard as it looks like he is the original creator of the dashboard. Would it be ok to add it to the repository?

**Comment by fberube** [comment]
Yes, of course, and I'm going to improve it this weekend.

**Comment by danielloader** [comment]
@fberube Sorry to ask, but I only see one revision of the dashboard @ https://grafana.com/grafana/dashboards/18089-spegel-stateless-cluster-local-oci-registry-mirror/

Is this still on the cards to align it with the latest metrics spegel exports?

Thanks
