### ISSUE TITLE
Document performance measuring

### ISSUE THREAD

**Issue by phillebaba** [spegel-org/spegel#4]
Currently it is difficult to measure performance differences between using Spegel and not using Spegel.

With the merging of containerd/containerd/pull/7313 it will be easier to measure pull speed per registry. This feature will be released in containerd 1.7. When the version is released the performance measuring should be documented for end users to compare the end result.

**Comment by dimm0** [comment]
Is there any way to at least see if it's working properly? Prometheus, logs, etc?

**Comment by phillebaba** [comment]
Requests are logged by each Spegel instance, so it is easy to see requests received. Additionally there are metrics that are exposed that are [documented](https://github.com/XenitAB/spegel/blob/main/docs/metrics.md). The metric `spegel_mirror_requests_total` would be a good indicator to look at.

I have had thoughts about building a UI to enable viewing where images are fetched from. The issue is that I do not really see a way to do that while staying true to the goal of keeping Spegel stateless.

**Comment by dimm0** [comment]
If I don't see the `spegel_mirror_requests_total` metric (both in prometheus and when directly querying the instances), does that mean it's not serving any images?

In logs I see a lot of "received image event" lines. Are those cache queries?

**Comment by phillebaba** [comment]
There is most likely something wrong with the mirror configuration. The image events occur when new images are pulled or updated. Requests are logged so you should see the logs in both the mirroring Spegel instance and the serving instance.

What type of Kubernetes flavor are you running? If it is not AKS or EKS it may require some additional Containerd configuration.

**Comment by phillebaba** [comment]
So Spegel creates the mirror configuration for you in `/etc/containerd/certs.d`. The important detail is that Containerd is configured to look for mirror configuration there. Check `/etc/containerd/config.toml` and make sure that it contains the required configuration. 

```toml
[plugins."io.containerd.grpc.v1.cri".registry]
   config_path = "/etc/containerd/certs.d"
```

This is not totally logical and can be frustrating when things do not work initially. I have created #155 to track a solution. It seems like easiest solution right now is to use the client to verify the configuration.

**Comment by dimm0** [comment]
Well, that path is not default. If you run `containerd config default`, it will be empty.
I'm adding it manually now to my configs.

**Comment by phillebaba** [comment]
An interesting thesis on performance measuring registries.

https://atlarge-research.com/pdfs/Petar_Galic_Master_Thesis_14_12_2020.pdf
