### ISSUE TITLE
Dashboard: ${DS_PROMETHEUS} was not found

### ISSUE THREAD

**Issue by mrclrchtr** [spegel-org/spegel#509]
Spegel version
0.0.23

Kubernetes distribution
Talos

Kubernetes version
1.30.1

CNI
Cilium

Thanks for adding the Grafana Dashboard.

Unfortunately I get the following message in Grafana when I turn it on:
```
Datasource ${DS_PROMETHEUS} was not found
```
![image](https://github.com/spegel-org/spegel/assets/16151098/f6b14b25-50c3-49a5-823e-d17bd3eb04bb)

What am I doing wrong?

I'm using kube-prometheus-stack.

_Originally posted by @mrclrchtr in https://github.com/spegel-org/spegel/issues/388#issuecomment-2157577038_

**Comment by davralin** [comment]
Same issue for me, I almost directly stole the flux-definitions from @onedr0p  - and I'm guessing it works for you?

Are you doing anything magical extra that I didn't catch in your repo?

**Comment by onedr0p** [comment]
It's broken for me too. I meant to get back to this but it fell off my radar, hopefully it can get fixed soon.

**Comment by AhmedTremo** [comment]
@onedr0p any luck for a fix here?, facing same issue with the grafana dashboard
