### ISSUE TITLE
Possible to default to remote registry pull?

### ISSUE THREAD

**Issue by Jay-Madden** [spegel-org/spegel#522]
I have been poking around the docs for a bit now and have not been able to ascertain if there is a configuration option to DEFAULT to a remote registry and only fall back to spegel in the event of the remote registry being unavailable.

I apologize if I missed the answer to this somewhere

**Comment by phillebaba** [comment]
No this feature is not present in Spegel neither do I thin it is feasible to implement. Why would you want to pull from the remote registry if the image is present locally?

**Comment by ewong-harmonicinc** [comment]
Spegel is a good tool to improve the reliability of image registry of a cloud service providers; however, image registry of cloud service provider is usually very fast and hence Spegel could not usually improve the speed but degrade the speed of image pulling. When our cluster is full of 2-core nodes, Spegel will degrade the image pull speed by more than one time.

**Comment by phillebaba** [comment]
This is the wrong issue to discuss this, if you have a problem with performance open a new issue.

**Comment by ewong-harmonicinc** [comment]
This may not be the fault of Spegel. The performance of Spegel depends on the VM.

**Comment by phillebaba** [comment]
Closing as we will not implement support for reversing the order of mirroring. If someone is interested in doing this, it could be done but would require some custom logic when creating the mirror configuration.
