### ISSUE TITLE
New joined nodes has error: "run/containerd/containerd.sock: connect: connection refused"

### ISSUE THREAD

**Issue by sonyafenge** [spegel-org/spegel#528]
### Spegel version

v0.0.18

### Kubernetes distribution

kubeadm

### Kubernetes version

v1.30

### CNI

calico

### Describe the bug

we are running kubernetes cluster on baremental machines using capi. I found any new joined nodes after spegel installation will have the error below and not function for any mirror.
```
{"level":"info","ts":1719427282.4200914,"caller":"state/state.go:30","msg":"running scheduled image state update"}
{"level":"error","ts":1719427282.4204097,"caller":"state/state.go:32","msg":"received errors when updating all images","error":"connection error: desc = \"transport: error while dialing: dial unix /run/containerd/containerd.sock: connect: connection refused\": unavailable","stacktrace":"github.com/xenitab/spegel/pkg/state.Track\n\t/build/pkg/state/state.go:32\nmain.registryCommand.func5\n\t/build/main.go:172\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78"}

```

**Comment by sonyafenge** [comment]
looks like same as: https://github.com/spegel-org/spegel/issues/333, not sure if that related leader election refresh.

**Comment by phillebaba** [comment]
This has nothing to do with #333. The error you are seeing comes from the Containerd client not being able to communicate with the Containerd socket.  Are you sure the socket is located at the path that is configured?

**Comment by sonyafenge** [comment]
yes, I am sure the socket is located at the path. everytime after I restart spegel daemonset, the issue was fixed.

**Comment by phillebaba** [comment]
This seems like a peculiar issue as restarting the pod should have no effect. And you are seeing the same issue with the latest Spegel version?

**Comment by sonyafenge** [comment]
still don't have a chance to test with the latest Spegel version, hopefully
i can get it tested next week.

**Comment by jurim76** [comment]
I have the same issue on control-plane nodes, regardless by restart

**Comment by phillebaba** [comment]
The error that you are seeing means that either the Containerd socket does not exist at that path or it can't be reached. This check is run immediately on start and will exit Spegel if an error occurs as there would be no use continuing. Are you sure that this is the correct path?

**Comment by jurim76** [comment]
Could not produce this issue anymore, please ignore

**Comment by phillebaba** [comment]
Closing as issues seem to be resolved.
