### ISSUE TITLE
Memory utilization question - possible leak / gc issue?

### ISSUE THREAD

**Issue by craig-seeman** [spegel-org/spegel#546]
### Spegel version

v0.0.23

### Kubernetes distribution

Normal / Bare Metal

### Kubernetes version

v1.29.6

### CNI

N/A

### Describe the bug

We have been running spegel in a test cluster (5-10 nodes) for a few weeks now and are noticing that there are times where the memory usage of one of the pods will sporadically jump and are wondering if this is common or expected. The normalized utilization is around 35MB and can be seen as a regular number for the previous few weeks, but we are noticing times where at times one or more of the pods will keep jumping up in increments up by up to double or more, sometimes leading them to be exceeding 1.7GB in size of the course of a few days.

When this happens, we had debug logging enabled and it appears to be aligned with when the memory affected pod (A) is doing a p2p advertisement of images at or around the same time of when another (B) is pulling - primarily or exclusively from another (C). However, there are also times where image pulls from (B or C) are being served from the affected pod (A).

<img width="1140" alt="Screenshot 2024-07-25 at 7 51 10 AM" src="https://github.com/user-attachments/assets/11b830cc-0d14-4481-86d2-34f64da8ad37">

<img width="712" alt="Screenshot 2024-07-24 at 11 39 21 AM" src="https://github.com/user-attachments/assets/5413f8eb-9ee4-4a07-833e-80c194b3a8de">
<img width="448" alt="Screenshot 2024-07-24 at 10 05 25 AM" src="https://github.com/user-attachments/assets/35fea114-d0c9-4a06-a13b-9a1bd0b6e196">

**Comment by phillebaba** [comment]
Thank you for the detailed report :rose: 

Looking at your graphs it feels like this is some sort of leak considering that the consumption is growing over time. This is sadly not something that I have observed myself. So it is going to be a fun one to reproduce. In my head there are two possible sources of this. Either there is some problem in libp2p somewhere. Or the something is leaking in the HTTP proxy. I will have a look through the code to see if there is something obvious that could cause this.

Out of interest are you serving very large images or is it just daily use causing this?

**Comment by phillebaba** [comment]
If possible could you dump the pprof data from the offending container the next time this happens. All you need to do is port forward to the containers metrics port and the use curl to get the data.

```
kubectl port-forward spegel-rvwt8 9090
```

```
curl -s http://127.0.0.1:9090/debug/pprof/heap > ./heap.out
curl -s http://127.0.0.1:9090/debug/pprof/profile?seconds=60 > ./cpu.out
```

**Comment by craig-seeman** [comment]
Bit of an update, I've been digging into this all day today - while I don't have any concrete things -- I'm getting a feeling this is more of an os/container situation possibly (or GC).

My reason for thinking this is that there is a statistic of working set vs memory I'm seeing here, and when I was doing some pprof debugging / datadog profiling, it was appearing that the heap was in a VERY reasonable state (I dont think it was over 15MB?) and nothing absurd was going on.

HOWEVER, One very interesting thing to note that leads me to believe it's more of an os/container level thing is around the fact that when I placed a limit/request on the daemonset, the memory utilization was getting up to that limit, but never exceeding and more importantly, was *not* causing an OOM. While I understand that it wont go over the limit, it's very telling to me that this is likely not the spegel code itself requesting / using the memory itself directly.

We are using a custom build here on our own images so i was able to kubectl exec in and play around with some statistics on the container itself while running and in a 'leaked' state. Something very interesting happened, I was loading some programs and doing an apt-install and the memory usage went down, leading me to believe something on the os layer was freed, completely unrelated to spegel code.

Here you can actually see _multiple_ pods that shot up in utilization - I was able to capture a log of everything that was downloaded at that time and was doing manual curls against the urls.
<img width="1207" alt="Screenshot 2024-07-26 at 9 32 27 AM" src="https://github.com/user-attachments/assets/a3f76edb-25e5-4b8a-ab19-631ab889b841">


Now, while not every time, once in a while one of the pods would get higher in memory - leading me to believe that this is more of an image pull(serve) situation vs the p2p part, however, with that being said I DO have to share that during my debugging here, I overwrote the ttl on the p2p broadcast to be 33 seconds to try to invoke it happening more.

As far as the images themselves being served, I'm not seeing any blobs on our usage that are above ~ 80MB in size, and when the pulls are happening and memory has a chance to shoot up, there are generally quite a few in flight from various locations, and around the time that this happens I see the response times of the http requests increase.


Hope this helps some!  I'm off for the weekend :)

**Comment by phillebaba** [comment]
This was a great read. Its getting late here but I thought I would share my thoughts before I forget them. This may be linked to the proxy server allocating memory. I have learnt a lot about the internals of Go http over the last few months. Which has lead me to do some refactoring and optimizations. It turns out that some details are a bit complicated. \

I have considered replacing the existing http proxy with my own request handler, mostly to get better control over what is going on. I realize that I don't really need all of the features offered by the http proxy. One aspect of this is the optional BufferPool that can be set in the proxy, which would reuse the same buffer over and over again instead of reallocating.

There is some more research needed but we may be in the right direction.

**Comment by craig-seeman** [comment]
I have an update / potential lead here :)

It's appearing that this is the result of the page cache between the system / container!

While digging through some metrics / stats I was able to come across the containerd metric of container.metric.cache which is the missing part of the overall utilization of the container minus the spegel binary memory itself!
<img width="377" alt="Screenshot 2024-08-02 at 12 21 44 PM" src="https://github.com/user-attachments/assets/05d0609e-f027-47e5-9cca-146ca1f55dd7">

```
# cat /sys/fs/cgroup/memory/memory.stat | grep cache
cache 90497024
total_cache 90497024
```

Here we can see the memory used (total)
<img width="582" alt="Screenshot 2024-08-02 at 12 24 25 PM" src="https://github.com/user-attachments/assets/9a6df092-32ba-436b-a74d-9dab3782d076">

And what was appearing / appears under almost all stats in the container itself - including the entire spegel binary in memory!
<img width="617" alt="Screenshot 2024-08-02 at 12 24 32 PM" src="https://github.com/user-attachments/assets/aaa6b2a9-10ca-4fcf-b894-38fb310b8809">


This lead me to the following ::
https://github.com/kubernetes/kubernetes/issues/43916#issuecomment-393228487

Perhaps there are some things that can be done with what you were saying in how spegel interacts with the container/host in caching/paging bits of memory it needs - particularly when serving blobs, but I'm not 100% certain.

Cheers~

**Comment by phillebaba** [comment]
I really think this is related to the fact that we are not setting our own buffer. Copying bytes between a HTTP response and request is not a zero copy sys call so it has to be buffered in userspace memory.

This results in the proxy consuming all remaining memory up to the limit. I would need to experiment with this but it should be possible to reproduce in a simpler context.

Thank you very much for the research. I am leaving on a bike trip for the next two weeks so I won't have access to a computer. Will try to start reproducing when I get back.

**Comment by craig-seeman** [comment]
Welcome back from the bike trip! Hope it was fun!

Quick little update on the situation using the merge from #573 I let it bake overnight and it still seems we have a little creepy 🕸️🕷️ bit of code crawling around somewhere! Ack! 

I apologize if this was simply some pre-work getting the buffer in place and I jumped the gun a bit too much to test it out :) I wanted to give you a heads up, too, since the application seems content/happy with life if a memory limit/request is placed on the kpod over the last month or so with no OOM to be seen; that this is not blocking myself from moving forward with deployment in the environment I'm looking to use this in (few thousand hosts across multiple clusters). I just wanted to make sure that was shared in the event you are prioritizing this instead of other feature work / improvement.

<img width="1400" alt="Screenshot 2024-09-04 at 8 59 10 AM" src="https://github.com/user-attachments/assets/ed8ec6eb-5872-45f5-8dbb-91cc5fd88fac">
