### ISSUE TITLE
Wrong grafana dashboard query

### ISSUE THREAD

**Issue by jurim76** [spegel-org/spegel#588]
### Spegel version

v0.0.24

### Kubernetes distribution

Kubeadm

### Kubernetes version

1.28

### CNI

Calico

### Describe the bug

`monitoring/grafana-dashboard.json` line 401

```
 "expr": "max(rate(http_request_duration_seconds_bucket{job=\"spegel\"})) [$__interval]"
 ```
 The `$__intreval` variable is not defined and range should be inside rate
 ```
  "expr": "max(rate(http_request_duration_seconds_bucket{job=\"spegel\"}[$__interval]))"
 ```

**Comment by phillebaba** [comment]
I am happy to take contributions if you want to fix this problem. I am currently not using the Grafana dashboard myself so I rely on the community to fix any potential problems.
