### ISSUE TITLE
Containerd registry config path needs to be set for mirror configuration to take effect

### ISSUE THREAD

**Issue by syedsalman3753** [spegel-org/spegel#640]
### Spegel version

v0.0.27

### Kubernetes distribution

Rancher kubernetes Engine (RKE)

### Kubernetes version

v1.22.9

### CNI

canal

### Describe the bug

All the spegel pods are failing with the below error

```
{"time":"2024-11-19T07:17:06.987651998Z","level":"ERROR","source":{"function":"main.main","file":"/build/main.go","line":86},"msg":"run exit with error","err":"Containerd registry config path needs to be set for mirror configuration to take effect"}
```

**Comment by phillebaba** [comment]
When you say RKE do you mean RKE1 or RKE2? I am not really sure if RKE1 is still in use which is why I ask.

As I understand it RKE2 is based on K3S which means that it should have Spegel embedded in the same way. If that is the case I suggest you use the embedded version instead.

We should also document this for future RKE2 users.

**Comment by syedsalman3753** [comment]
@phillebaba 
I have created the RKE1 Kubernetes cluster with version 1.22.9
K8S cluster nodes - ubuntu

Need documentation on how to setup spegel on this cluster

**Comment by phillebaba** [comment]
Version 1.22.9 sounds like a very old Kubernetes version, are you sure this is right?

I just checked the documentation which states that RKE1 still uses Docker as its runtime, while RKE2 uses Containerd. Spegel only supports Containerd right now so I cant really help you with getting things running on your setup.

**Comment by syedsalman3753** [comment]
Ohk...

will close the issue

Thanks for the information @phillebaba
